U ibranch
eriwang/Ensemble-Old pull request #9
Opened 2018-05-15 16:43 UTC by IndignantToaster

Super simple stuff...maybe only things to address would be spacing and some "questionable names".  Evn the CSS is placeholder just to make it easier to test with, so that's all stuff that will prolly be changed.  I need to understand what and how this app is gonna work more if we want to make a UI tho............

2018-05-17 02:54 UTC, eriwang requested changes

2018-05-17 02:54 UTC, eriwang commented on stylesheet.css
> +body {
Let's move this entire file to the `static/` directory

2018-05-17 02:54 UTC, eriwang commented on stylesheet.css
> +body {
I personally prefer using `<div id="content"...`, I think it gives a little more control for future things we might add, though right now it's functionally the same

2018-05-17 02:54 UTC, eriwang commented on stylesheet.css
> +    display: flex;
Is the flex css necessary for an empty div?

2018-05-17 02:54 UTC, eriwang commented on stylesheet.css
> +#mainWindow {
I personally prefer `main-window`, which i think is the widely used convention (it looks a bit more consistent with HTML and CSS code if you ask me, where capital letters are rare), but your call

2018-05-17 14:22 UTC, IndignantToaster commented on stylesheet.css
> +#mainWindow {
camel case is love, camel case is life.  but fine.

2018-05-17 14:22 UTC, IndignantToaster commented on stylesheet.css
> +    display: flex;
nop, guess not

2018-05-17 14:24 UTC, IndignantToaster commented on stylesheet.css
> +body {
consider it done.

2018-05-17 14:26 UTC, IndignantToaster commented on stylesheet.css
> +body {
ooooooooooooooooooook

2018-05-18 15:57 UTC, eriwang requested changes

2018-05-18 15:57 UTC, eriwang commented on static/stylesheet.css
> +#uploadButton {
You missed one

2018-05-18 15:57 UTC, eriwang commented on static/stylesheet.css
> +body {
What does having a body with this as well as a content div that has the same thing do??

2023-01-18 18:08 UTC, closed without merging